# yaml-language-server: $schema=https://json-schema.org/draft-07/schema

title: Networking config schema
properties:
  nodes:
    type: object
    patternProperties:
      ^N\d$:
        type: object
        properties:
          MAC:
            type: string
            minLength: 2
            maxLength: 2
          IP:
            type: number
            minimum: 0x0
            exclusiveMaximum: 0x100
          port:
            type: number
        additionalProperties: false
        required:
          - MAC
          - IP
          - port
    additionalProperties: false
  wires:
    type: array
    items:
      type: object
      properties:
        nodes:
          type: array
          items:
            type: string
            pattern: ^N\d$

additionalProperties: false
